language: c
script: make check

matrix:
  include:

  # Clang 32 bit
  - compiler: clang
    env: CFLAGS=-m32
    addons:
      apt:
        packages:
        - gcc-multilib

  # Clang 64 bit
  - compiler: clang
    env: CFLAGS=-m64

  # GCC
  - compiler: gcc

  # Mac
  - compiler: clang
    os: osx
    env: CFLAGS="-arch i386 -arch x86_64"

  # Windows 32 bit
  - compiler: i686-w64-mingw32-gcc
    env: RUN=wine
    script: make -f Makefile.msys check
    addons:
      apt:
        packages:
        - binutils-mingw-w64-i686
        - gcc-mingw-w64-i686
        - wine1.4-i386

  # Windows 64 bit
  - compiler: x86_64-w64-mingw32-gcc
    env: RUN=wine64
    script: make -f Makefile.msys check
    addons:
      apt:
        packages:
        - binutils-mingw-w64-x86-64
        - gcc-mingw-w64-x86-64
        - wine1.4-amd64
