language: c
addons:
  apt:
    packages:
     - gcc-multilib
     - binutils-mingw-w64-i686
     - binutils-mingw-w64-x86-64
     - mingw-w64-dev
     - gcc-mingw-w64-base
     - gcc-mingw-w64-i686
     - gcc-mingw-w64-x86-64
     - wine1.4-common
     - wine1.4-i386
     - wine1.4-amd64
     - wine1.4
script:
 - CC=clang CFLAGS=-m32 make clean check
 - CC=clang CFLAGS=-m64 make clean check
 - CC=gcc               make clean check
 - CC=i686-w64-mingw32-gcc   RUN=wine   make clean check -f Makefile.msys
 - CC=x86_64-w64-mingw32-gcc RUN=wine64 make clean check -f Makefile.msys
