language: c
script: make check

matrix:
  include:

  # Linux 32 bit
  - compiler: clang
    env: CFLAGS=-m32
    addons:
      apt:
        packages:
        - gcc-multilib

  # Linux 64 bit
  - compiler: clang
    env: CFLAGS=-m64

  # Linux ARM (Raspberry Pi)
  - compiler: arm-linux-gnueabihf-gcc
    dist: trusty
    sudo: false
    script: make
    addons:
      apt:
        packages:
        - libc6-dev-armhf-cross
        - gcc-arm-linux-gnueabihf

  # Mac
  - compiler: clang
    os: osx
    env: CFLAGS="-arch i386 -arch x86_64"

  # Windows 32 bit
  - compiler: i686-w64-mingw32-gcc
    env: RUN=wine
    script: make -f Makefile.msys check
    addons:
      apt:
        packages:
        - binutils-mingw-w64-i686
        - gcc-mingw-w64-i686
        - wine1.4-i386

  # Windows 64 bit
  - compiler: x86_64-w64-mingw32-gcc
    env: RUN=wine64
    script: make -f Makefile.msys check
    addons:
      apt:
        packages:
        - binutils-mingw-w64-x86-64
        - gcc-mingw-w64-x86-64
        - wine1.4-amd64
